FROM node:20-alpine AS dev
WORKDIR /app
COPY frontend/app/package.json frontend/app/package-lock.json* ./
RUN npm install
COPY frontend/app /app
EXPOSE 5173
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
